### PR TITLE
correct docker compose command, add EXTRA_CMD_ARG debug example

### PR DESCRIPTION
**Pull request by waltervl**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the changes, could you undo the change from 'docker-compose' to 'docker compose' ? docker-compose is something else then docker (with compose)

**Comment by waltervl** [comment]
Nice confusion again...... User notes that he had to use docker compose up instead of docker-compose... So what is right?

**Comment by gizmocuz** [comment]
if we ask to install docker-compose, I think we mean docker-compose?

**Comment by gizmocuz** [comment]
Also I think instead of a mega big example string as possible arguments (and there are many), it might be best to point either list them all (like executing domoticz --help) or maybe refer to a wiki page
That keeps this page cleaner

**Comment by waltervl** [comment]
From the wiki page it is not clear we request to install docker-compose. Also we link to the docker desktop install. Docker compose is part of docker desktop. So no need to install docker-compose.

We should decide to put the docker install and usage on the docker readme and hub or on the wiki. As else we need to update the instructions on all platforms. I propose to make a basic instruction on Docker readme/hub and refer to wiki for detailed instructions. We do now the other way around....

**Comment by gizmocuz** [comment]
You can of course install with docker and docker-compose
The docker-compose example is for ….. docker-compose

There are many many dockers and I think we share the same info on our readme’s
It is not a tutorial how to install docker/docker-compose or how to use it
I think that is for the end user and there are many (many) sites explaining this
Of course we could dedicate a section for it on our wiki
But this readme should be clear and simple
Explaining the domoticz commandline arguments should not be part of this and are explained elsewhere
Of course placing a link to more detailed instructions can be added

**Comment by waltervl** [comment]
Just leave some docker hub links to show:
No docker hub instructions and instructions linked to project docs
https://hub.docker.com/r/koenkk/zigbee2mqtt
https://hub.docker.com/r/zwavejs/zwave-js-ui
https://hub.docker.com/r/homeassistant/home-assistant
https://hub.docker.com/r/jeedom/jeedom

Full instructions on Docker hub
https://hub.docker.com/r/openhab/openhab

I think the majority supports my proposal :-)

**Comment by gizmocuz** [comment]
Either we leave it as it is, or as I mentioned before we could add a link to more in-depth instructions
For sure I don't want to change docker-compose to docker compose or add additional examples to the extra parameters as they we will end up with 20 possible parameters (hence a link to additional information would be the sollution)

**Comment by gizmocuz** [comment]
I modified the readme, hope this is more to your likening

**Comment by waltervl** [comment]
Yes is fine. Perhaps also advise to pull stable in the default docker pull command. Now they would pull latest if they do not use a release tag as proposed which leads to a beta.

**Comment by gizmocuz** [comment]
Yeah I thought about that, but I think the beta's are pretty safe and should be checked first...

**Comment by waltervl** [comment]
> Yeah I thought about that, but I think the beta's are pretty safe and should be checked first...

If you want to move first time Domoticz users to docker I definitely do not agree....

**Comment by gizmocuz** [comment]
Well yes I know you got a point here .... I will change it so it is default stable 😁
Best wishes for 2023!!

**Comment by gizmocuz** [comment]
Done, and I just noticed there was already a link to the command line arguments on the wiki...

**Comment by waltervl** [comment]
Thanks! And the best wishes for you too!

**Pull request closed without merging**
