### PR TITLE
implements items raised as questions in issue 25

### PR DESCRIPTION
**Pull request by Paraphraser**
Changes (numbers correspond with questions):

1. `customstart.sh` sourced after persistent store is populated (Q1).

2. Ensures all path components below exist and, if necessary, are recreated on each launch:

	```
	/opt/domoticz/userdata/scripts/dzVents/data
	```

3. Assumes answer to Q3 is,:

	> Domoticz Easy Events examples should be placed in
	`scripts/dzVents/examples`

4. Working directory reset after source statement completes (Q4).

5. Adds template `customstart.sh` (execute bit not set; script is sourced) as an alternative to editing
[domoticz Wiki](https://www.domoticz.com/wiki/Docker#custom_startup_script_for_the_container) where I do not have an account.

Tested with the following Dockerfile:

```
FROM domoticz/domoticz:stable
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
```

> Assumes `chmod +x docker-entrypoint.sh` prior to build.

Tests:

1. No persistent store. Initialises properly, including Domoticz Easy Events examples in `scripts/dzVents/examples`.
2. Removing `scripts` re-populates on restart.
3. Removing `scripts/dzVents` re-populates on restart.
4. Adding template `customstart.sh` executes as intended:

	```
	$ docker logs domoticz
	updating packages list
	installing packages
	Reading package lists...
	Building dependency tree...
	Reading state information...
	The following additional packages will be installed:
	  libcap2 libcap2-bin libcjson1 libmosquitto1 libpam-cap The following NEW packages will be installed: iputils-ping libcap2 libcap2-bin libcjson1 libmosquitto1 libpam-cap mosquitto-clients

	…

	2024-05-29 16:16:52.889  Status: Domoticz V2024.4 (c)2012-2024 GizMoCuz
	2024-05-29 16:16:52.889  Status: Build Hash: 731719420, Date: 2024-01-30 19:16:34

	…

	```

Fixes: #25

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for the PR!!
I don't think the customstart.sh should be included in this PR as this is personal....

**Comment by Paraphraser** [comment]
Well, it's up to you. Your repo, your rules. If you want me to update the PR branch to omit it, I'm happy to do that. Just say the word.

It did occur to me, though, that if I was building something like domoticz-docker either for my own use or for [IOTstack](https://github.com/SensorsIot/IOTstack) where I do a lot of work, the way I would handle something like `customstart.sh` would be to copy it into the image and then have the entry point script copy it into place in the persistent store. That way a working known-good "default" would always be there ready for the user to edit. I reckon it's a bit of a pain for users to have to find things in places like a Wiki, copy and paste, deal with problems like Windows adding CR+LF and so on. Much better if the basic template is there already - along with the assurance that if the user mucks up an edit, the fix is to just delete the busted file, restart the container, and try again.

Still, this is all just my two cents on the topic. I have no skin in this game. I'm really only getting involved to help out a friend.

**Comment by gizmocuz** [comment]
Well the thing is, adding this file, with the current content is making it slow at the initial start and also installs stuff that is not needed for most users

```
echo "updating packages list"
	apt-get -qq update

	echo "installing packages"
	apt-get -y install mosquitto-clients iputils-ping
```

On the main docker page it is explained how to use this file, and I expect users to read the manual before they 'experiment' 😊

you could name it customstart.sh.sample ? or something simular?

**Comment by Paraphraser** [comment]
I think we might be talking about different things.

While it is true that anything (eg `customstart.sh`) which is in the same directory as the Dockerfile is **available** in the Docker build context, absent an explicit COPY statement, the file isn't going to make it into the image.

### Begin hypothetical...

> Until I say otherwise, this is all HYPOTHETICAL. I'm not saying "do this". I'm not recommending anything. I'm just trying to explain the situation.

Let's assume, for the moment, we added a COPY statement to the Dockerfile. Something like this:

```
...
COPY docker-entrypoint.sh /usr/local/bin/
COPY customstart.sh /opt/domoticz/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh \
    && ln -s usr/local/bin/docker-entrypoint.sh / # backwards compat
...
```

> As an aside, notice how you had to COPY `docker-entrypoint.sh` into the image. If that COPY wasn't there in your current Dockerfile, `docker-entrypoint.sh` wouldn't get into the image.

The same applies to `customstart.sh`. If there's no COPY then the file doesn't make it into the image. I hope that makes sense.

Now let's assume we've added that COPY. The file is now in the image at the internal path:

```
/opt/domoticz/customstart.sh
```

What's the entry-point script looking for?

```
/opt/domoticz/userdata/customstart.sh
```

Different path, right? Thus in order for `customstart.sh` to be found where entry-point is searching would need something *extra*, such as these lines in the entry-point script:

```
if [ ! -f /opt/domoticz/userdata/customstart.sh ]; then
   cp /opt/domoticz/customstart.sh /opt/domoticz/userdata/customstart.sh
fi
source /opt/domoticz/userdata/customstart.sh
cd /opt/domoticz
```

> Or, in words, if it ain't there, put it there and, then, because it's now guaranteed to be there, source it.

To sum up, you would have to do all that **before** `customstart.sh` would be installed and executed automatically when the container launched. Again, I hope that makes sense.

Now, **IF** you thought it was a good idea to do it that way **THEN** I would definitely agree with the rest of your proposition that the default `customstart.sh` should not do anything too time-consuming. It should either have something like:

```
# this script (customstart.sh) is SOURCED by docker-entrypoint.sh

# if you want to activate this script, remove or comment-out the next line
return
...
```

or the `apt-get` commands should be commented-out.

So, yes, I **get** the point you're making about slow starts. My point is that it isn't happening. Nevertheless, I'm happy to rename as you suggest but I'll come back to that a bit further down.

### ... end hypothetical

<hr>

Now, put a pin in all of that.

The only reason I added `customstart.sh` to the pull request is because:

1. I didn't want to figure out how to edit the Wiki.
2. I thought the structure of the example in the Wiki masked its intention and made it harder to understand than necessary, particularly for people who don't work with `bash` all the time. The Wiki example also has a bug but that's sort of beside the point.
3. I thought that including it in the PR would be a simple way of making it available.

I assume you **do** have the ability to edit the Wiki so maybe the best way forward here is for me to delete it from the PR but for you to edit the Wiki to add it. Yes/no?

Also, I take your point about expecting users to read the manual. I put a lot of time into the IOTstack Wiki and I would *love* for IOTstack users to be thoroughly familiar with everything it says. It would save bags of time debugging problems if they'd just RTFM.

It's just that my experience (with IOTstack, and all my former lives in 50-odd years of an IT career) is that the average user just fires it up, expects it to work, and gets grumpy when it doesn't.

Thus, as well as writing heaps of doco, I also try my best to improve containers so they always self-initialise properly with sensible defaults. I generally do it with custom Dockerfiles rather than the `customstart.sh` approach because, like you, I believe container launch speed is an important factor.

So if, for example, the mosquitto clients were something that most domoticz users were going to need, I'd be recommending adding those via your Dockerfile rather than via `customstart.sh`.

But maybe I've just been unlucky with my user base. Maybe all Domoticz users are sophisticated enough to realise that reading the manual before touching anything really is a darn good idea. 😃

<hr>

To cut to the chase, do you want me to:

1. Delete `customstart.sh` from the pull request.
2. Rename `customstart.sh` to `customstart.sh.sample`.
3. Do nothing.

I'll leave it to you to decide what to do, if anything, about the Domoticz Wiki.

**Comment by gizmocuz** [comment]
Thanks!! Looks you are certainly known what you're talking about 😁Great!

Okey, if I understand correctly (and I hope I am right), we could make a 'pseudo' customstart.sh script that contains only remarks but can act as an example
When installing the docker, or when updating an existing container, via a 'if it is not here, copy it to the users local 'config' folder' ....
That would also be great! So users only have to add their install/actions and done.
Just make sure that if there is already a file customstart.sh that this will not be replaced with the 'pseudo' file

If this is possible, and you could add it in the PR, that would be awsome!

Maybe you can also add a (commented) line so show how to add additional python plugins like

#pip3 install aiohttp

**Comment by Paraphraser** [comment]
OK. I'm happy to do that. Maybe give me until next week - some other stuff has come I that I have to attend to first.

On the subject of pip - and as a heads-up - if you change the base container to be Bookworm then Python "security features" kick in. Python thinks you're running as root (which you are) and gets snippy and tries to guide you towards using a venv. There's a workaround (`--break-system-packages`) but it's a pest for users and I'm not sure how long-term it is.

**Comment by gizmocuz** [comment]
The reason is that some hardware needs root access (aldo not many anymore)

Yes the idea is to upgrade to bookworm soon... 

Maybe this could solve the issue:

https://stackoverflow.com/questions/68673221/warning-running-pip-as-the-root-user

**Comment by Paraphraser** [comment]
Yes - exactly that problem. Passing that flag silences the warning and reverts to the previous behaviour when pip/pip3 are running as root or via sudo.

**Comment by Paraphraser** [comment]
And, to be clear, I agree that there's a valid case if you have a base system and you're trying to decide whether to install something globally for all users vs the current user. Shoving stuff into a venv definitely limits the attack surface if someone slips some malware into the supply chain.

But it doesn't take account of containers where the environment is already contained and, in effect, amounts to its own venv. It's really a single-user environment already. This is an argument I have all the time in other places. Providing you **think** about what a container needs access to, you can use device or cgroup rules, read-only flags and the like to lock it down to exactly what is needed and, once you've done that, who cares about root? Still, just one person's view...

**Comment by Paraphraser** [comment]
New commit pushed to PR. See the commit log for a detailed explanation. I hope it meets your needs.

**Comment by Paraphraser** [comment]
Yes, I can do that.

But the existing structure was starting to get a bit unwieldy and I always find that troublesome. In particular, having an "if-then" gated on the absence of a path, wasn't going to do much for existing deployments. Ideally, existing users would also get the plugins and web templates once you pushed an updated image to DockerHub. That wouldn't happen with the existing structure. I thought that was suboptimal.

So I've taken the opportunity to go back a step and re-do the "self repair" code using `rsync`. This is the technique I've used in other containers. I've added `rsync` in the Dockerfile and then used it in the entry-point script. The key benefit is it will repair **anything** from a single file being removed anywhere in the persistent store, through a folder structure, all the way up to the whole persistent store being erased.

See what you think. Try deleting bits and pieces and restarting the container. Things come right back!

> possible to copy (if not exists) the www/templates to the users data folder (mounted volume) as well as the 'plugins' folder?

I wasn't exactly sure what structure you were asking for here. What I've done in this commit is to copy:

```
/opt/domoticz/www/templates
```

to:

```
/opt/domoticz/userdata/www/templates
```

If you really wanted a copy of the entire `www` folder (not just the templates sub-folder) then I can do that.

**Comment by gizmocuz** [comment]
Thank you for all the work and patience!!!

No need for the entire www folder, only the templates folder.
This is a special folder where users can add their own pages in like:

https://www.domoticz.com/forum/viewtopic.php?t=42345&start=80

The initial content of this folder is to help them get started

Same for the plugins folder, it would be great to only copy/sync the examples folder

**Comment by Paraphraser** [comment]
Done!

**Comment by gizmocuz** [comment]
Wonderful! Thank you for this!

Only thing that does not need to be copied is /scripts/template

This is used internally when you create a new dzVents event and you see the menu popup with these templates

**Comment by Paraphraser** [comment]
Can I please clarify what you mean because I think this might represent a change from what is happening now (before any changes made by this pull request). The original code:

```
if [ ! -d "/opt/domoticz/userdata/scripts" ]; then
        mkdir -p /opt/domoticz/userdata/scripts
        mkdir -p /opt/domoticz/userdata/scripts/dzVents/data
        cp -R /opt/domoticz/scripts/templates /opt/domoticz/userdata/scripts
        cp -R /opt/domoticz/scripts/dzVents/examples /opt/domoticz/userdata/scripts
fi
```

That first `cp` copies `scripts/templates`. So please confirm you no longer want that the circled folder or its contents but that everything else is as you want.

 IMG_2619

**Comment by gizmocuz** [comment]
Yes, that is correct. This folder is not needed to be copied. It needs to stay private as only domoticz is using this internally

**Comment by Paraphraser** [comment]
Done.

**Comment by gizmocuz** [comment]
Thank you very much for this!! I will update the docker build servers a.s.a.p. with the changes!

**Comment by Paraphraser** [comment]
You're welcome. It has been a pleasure.

**Comment by gizmocuz** [comment]
Hmmm... I updated an existing docker installation but in mij volume (folder) these two lines seem not to work

rsync -airp --ignore-existing          "${TEMPLATE}/customstart.sh"           "${USERDATA}"
rsync -airp --ignore-existing --mkpath "${TEMPLATE}/www/templates"            "${USERDATA}/www"

I have no customstart.sh or the (missing) files in www/templates
(I just have one file in the local template folder)

My docker compose file looks like documented here:

https://hub.docker.com/r/domoticz/domoticz

```
    volumes:
      - ./config:/opt/domoticz/userdata
      - ./config/www/templates:/opt/domoticz/www/templates
```

Should it have worked? Or is it only at new installs?

**Comment by Paraphraser** [comment]
Awake now - combination of a late night and UTC+10 -  and starting to look at this. I'm pretty sure I understand the reason but I'd like to work through it so I can explain it to you.

**Comment by Paraphraser** [comment]
I'll start with **my** service definition (the one I used to test all the changes in this PR):

```
domoticz:
  container_name: domoticz
  image: domoticz/domoticz:latest
  x-image: domoticz/domoticz:stable
  restart: unless-stopped
  environment:
    - TZ=${TZ:-Etc/UTC}
    # - LOG_PATH=/opt/domoticz/userdata/domoticz.log
    # - EXTRA_CMD_ARG=
  ports:
    - "8083:8080"
    - "1443:443"
  volumes:
    - ./volumes/domoticz:/opt/domoticz/userdata
  x-devices:
    - "/dev/serial/by-id/usb-0658_0200-if00-port0:/dev/ttyACM0"
```

> if you haven't encountered `x-` prefixes before, they have the same effect as commenting-out all the lines in the clause.

My service definition is based on the [IOTstack service definition](https://github.com/SensorsIot/IOTstack/blob/master/.templates/domoticz/service.yml).

> I'm not saying the IOTstack service definition is somehow "correct", merely that I'm coming at Domoticz from that perspective.

For whatever reason, IOTstack only has a single `volume` mapping whereas yours has two. Also, for context, the IOTstack convention is that the persistent store for every container starts at:

```
- ./volumes/«containerName»
```

whereas random service definitions found on the web have their own conventions. I'll start with yours:

```
- ./config:/opt/domoticz/userdata
- ./config/www/templates:/opt/domoticz/www/templates
```

and transform mine to the equivalent structure:

```
- ./config:/opt/domoticz/userdata
```

Thus my first line is functionally identical to yours, right?

Now, assume a blank slate situation and tell `docker-compose` to launch Domoticz. What `docker-compose` does for that first volume mapping is the equivalent of this:

```
$ sudo mkdir -p ./config
$ docker exec domoticz mkdir -p /opt/domoticz/userdata
$ docker exec domoticz mount --bind /opt/domoticz/userdata ./config 
```

The third command won't actually work like that. I'm just trying to explain what Docker does. In words:

1. the external (left hand side) path is created in the local file system.
2. the internal (right hand side) path is created in the container file system.
3. the internal path becomes a mount-point connecting to the external path.

The `mkdir` commands are fail-safes. Nothing happens if the path passed to `mkdir` already exists.

It's the "mount" that's important. With **all** "mount" operations, if the mount-point folder has any content before the mount, that content becomes inaccessible after the mount. This is why entry-point scripts need to copy stuff around at container launch time - those internal paths always start out being empty **inside the container**. The container only ever sees what is **outside** the container at the external path. If the external path is empty, so is the internal path.

> If that last paragraph doesn't make sense immediately then please read it a few times until it clicks because it explains what is happening on your system.

So, assume `docker-compose` has just processed:

```
- ./config:/opt/domoticz/userdata
```

Now `docker-compose` comes to the second volume mapping:

```
- ./config/www/templates:/opt/domoticz/www/templates
```

The same process:

1. A protective (`mkdir -p`) of the external path.
2. A protective (`mkdir -p`) of the internal path.
3. Mount the external path at the internal path.

See what has happened? All the content at the internal path has just become inaccessible. Any command running inside the container like this:

```
cp -r /opt/domoticz/www/templates «some destination path»
```  

is going to find the source directory is **empty** so there's nothing to copy.

<hr>

I can demonstrate all this but first I need to transform the volume mappings in your service definition to adopt IOTstack conventions:

```
- ./volumes/domoticz:/opt/domoticz/userdata
- ./volumes/domoticz/www/templates:/opt/domoticz/www/templates
```
	
I'm also going to use the `:stable` tag so I can show this was happening before the pull request was applied.

```
$ grep -A 16 "^  domoticz:" docker-compose.yml 
  domoticz:
    container_name: domoticz
    x-image: domoticz/domoticz:latest
    image: domoticz/domoticz:stable
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
      # - LOG_PATH=/opt/domoticz/userdata/domoticz.log
      # - EXTRA_CMD_ARG=
    ports:
      - "8083:8080"
      - "1443:443"
    volumes:
      - ./volumes/domoticz:/opt/domoticz/userdata
      - ./volumes/domoticz/www/templates:/opt/domoticz/www/templates
    x-devices:
      - "/dev/serial/by-id/usb-0658_0200-if00-port0:/dev/ttyACM0"

$ sudo rm -rf ./volumes/domoticz

$ docker-compose up -d domoticz
[+] Running 1/1
 ✔ Container domoticz  Started                                                                                                                             1.2s 

$ tree ./volumes/domoticz/www
./volumes/domoticz/www
└── templates

1 directory, 0 files

$ docker exec domoticz ls -lR /opt/domoticz/www/templates
/opt/domoticz/www/templates:
total 0

$ docker-compose down domoticz
[+] Running 3/1
 ✔ Container domoticz          Removed                                                                                                                     3.3s 
```

So, the `tree` command shows there's nothing other than the result of the protective `mkdir` at the external path, while the `ls` shows there's nothing at the internal path **because it's being masked by the mount**.

Now I'll move the goal-posts by deactivating that second `volume` map and repeat the test:

```
$ grep -A 16 "^  domoticz:" docker-compose.yml 
  domoticz:
    container_name: domoticz
    x-image: domoticz/domoticz:latest
    image: domoticz/domoticz:stable
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
      # - LOG_PATH=/opt/domoticz/userdata/domoticz.log
      # - EXTRA_CMD_ARG=
    ports:
      - "8083:8080"
      - "1443:443"
    volumes:
      - ./volumes/domoticz:/opt/domoticz/userdata
      # - ./volumes/domoticz/www/templates:/opt/domoticz/www/templates
    x-devices:
      - "/dev/serial/by-id/usb-0658_0200-if00-port0:/dev/ttyACM0"

$ sudo rm -rf ./volumes/domoticz

$ docker-compose up -d domoticz
[+] Running 1/1
 ✔ Container domoticz  Started                                                                                                                             0.9s 

$ tree ./volumes/domoticz/www
./volumes/domoticz/www [error opening dir]

0 directories, 0 files

$ docker exec domoticz ls -lR /opt/domoticz/www/templates
/opt/domoticz/www/templates:
total 16
-rw-r--r-- 1 1000 1000 2790 Nov 30  2023 angular.example
-rw-r--r-- 1 1000 1000 6962 Dec 18 18:25 custom.example
-rw-r--r-- 1 1000 1000  269 Nov 30  2023 readme.txt
```

So, the `tree` failed because the external path on the commented-out `volume` statement never got executed but, internally, the templates directory has content because it isn't being used as a mount point.

I'm sure you see where I'm going with this. I don't think that second `volume` mapping has ever worked. If you're seeing stuff in `./config/www/templates` on your own system then I'm pretty sure it got there some way *other* than this mapping. Thus my initial recommendation would be to lose that line.

<hr>

Now I'll move to a slightly more general question. Let's assume there's a user (eg you) who has been using the "two volumes" config and now wants to migrate to the `latest` image.

Let's create the initial conditions:

```
$ grep -A 16 "^  domoticz:" docker-compose.yml | grep "image:"
    x-image: domoticz/domoticz:latest
    image: domoticz/domoticz:stable

$ grep -A 16 "^  domoticz:" docker-compose.yml | grep -A 2 'volumes:'
    volumes:
      - ./volumes/domoticz:/opt/domoticz/userdata
      - ./volumes/domoticz/www/templates:/opt/domoticz/www/templates

$ sudo rm -rf ./volumes/domoticz

$ docker-compose up -d domoticz
[+] Running 1/1
 ✔ Container domoticz  Started                                                                                                                             1.1s 

$ docker-compose down domoticz
[+] Running 3/1
 ✔ Container domoticz          Removed                                                                                                                     2.9s 
```

Now, migrate to `latest`:

```
$ grep -A 16 "^  domoticz:" docker-compose.yml | grep "image:"
    image: domoticz/domoticz:latest
    x-image: domoticz/domoticz:stable
```

I won't change the two-volume-maps. I'll just bring up the container. What did self-repair do?

```
$ docker logs domoticz
2024-06-08 11:39:00.812  Launch: Begin container self-repair
cd+++++++++ examples/
>f+++++++++ examples/BaseTemplate.py
>f+++++++++ examples/DenonMarantz.py
>f+++++++++ examples/Dlink DSP-W215.py
>f+++++++++ examples/HTTP Listener.py
>f+++++++++ examples/HTTP.py
>f+++++++++ examples/Kodi.py
>f+++++++++ examples/MQTT Publish.py
>f+++++++++ examples/MQTT Subscribe.py
>f+++++++++ examples/Mutli-Threaded.py
>f+++++++++ examples/Pinger.py
>f+++++++++ examples/RAVEn.py
>f+++++++++ examples/UDP Discovery.py
>f+++++++++ examples/Web Socket Client.py
>f+++++++++ customstart.sh
cd+++++++++ examples/
>f+++++++++ examples/calc temp delta.lua
>f+++++++++ examples/check battery levels.lua
>f+++++++++ examples/check dead devices by desc.lua
>f+++++++++ examples/check dead devices.lua
>f+++++++++ examples/external_light.lua
>f+++++++++ examples/fake presence.lua
>f+++++++++ examples/garage door.lua
>f+++++++++ examples/get sensor values.lua
>f+++++++++ examples/intruder alert.lua
>f+++++++++ examples/leak_detection.lua
>f+++++++++ examples/notify for dead system-alive check devices.lua
>f+++++++++ examples/only run script when button pressed.lua
>f+++++++++ examples/plant watering notification.lua
>f+++++++++ examples/random night light.lua
>f+++++++++ examples/respond to switch.lua
>f+++++++++ examples/schedule fish pond pump.lua
>f+++++++++ examples/simple room heating with hysteresis control.lua
>f+++++++++ examples/sunscreen.lua
2024-06-08 11:39:01.120  Launch: End container self-repair
2024-06-08 11:39:01.128  Launch: Running customstart.sh
…
```

It's done a fair bit of work, including adding `customstart.sh`

```
$ head -3 ./volumes/domoticz/customstart.sh
# this script (customstart.sh) is SOURCED by docker-entrypoint.sh

# This script is run whenever the container launches (eg "docker run" or
```

which is the new script. Now, what about the second volume mapping:

```
$ tree ./volumes/domoticz/www
./volumes/domoticz/www
└── templates

1 directory, 0 files

$ docker exec domoticz ls -lR /opt/domoticz/www/templates
/opt/domoticz/www/templates:
total 0
```

So, as explained before, the `mkdir` and `mount` operations have resulted in an empty shared folder. What happens if I create some files?

```
$ touch ./volumes/domoticz/www/templates/created-externally
$ docker exec domoticz touch /opt/domoticz/www/templates/created-internally

$ tree ./volumes/domoticz/www
./volumes/domoticz/www
└── templates
    ├── created-externally
    └── created-internally

$ docker exec domoticz ls -lR /opt/domoticz/www/templates
/opt/domoticz/www/templates:
total 0
-rw-r--r-- 1 1000 1000 0 Jun  8 11:45 created-externally
-rw-r--r-- 1 root root 0 Jun  8 11:45 created-internally

$ rm ./volumes/domoticz/www/templates/created-*
rm: remove write-protected regular empty file './volumes/domoticz/www/templates/created-internally'? y
```

> `docker exec` runs as root inside the container which is why the file winds up with root ownership. If I had restarted the container before running the `rm` command, the recursive `chown` would have fixed that on-the-fly.

The material point, of course, is that that second volume mapping "works" in the sense of creating a relationship between an internal folder and a persistent store. Anything the user (or anything else) places in the folder using either the internal or external path will persist. It's just that the container itself can't populate it because the "mount" has made the required content inaccessible.

Finally, let's see what happens if we lose the second volume-mapping:

```
$ grep -A 16 "^  domoticz:" docker-compose.yml | grep -A 2 'volumes:'
    volumes:
      - ./volumes/domoticz:/opt/domoticz/userdata
      # - ./volumes/domoticz/www/templates:/opt/domoticz/www/templates

$ docker-compose up -d domoticz
[+] Running 1/1
 ✔ Container domoticz  Started                                                                                                                             4.3s 

$ docker logs domoticz
2024-06-08 11:48:29.828  Launch: Begin container self-repair
.d..t...... templates/
>f+++++++++ templates/angular.example
>f+++++++++ templates/custom.example
>f+++++++++ templates/readme.txt
2024-06-08 11:48:30.064  Launch: End container self-repair
…

$ tree ./volumes/domoticz/www
./volumes/domoticz/www
└── templates
    ├── angular.example
    ├── custom.example
    └── readme.txt

$ docker exec domoticz ls -lR /opt/domoticz/www/templates
/opt/domoticz/www/templates:
total 16
-rw-r--r-- 1 1000 1000 2790 Nov 30  2023 angular.example
-rw-r--r-- 1 1000 1000 6962 Dec 18 18:25 custom.example
-rw-r--r-- 1 1000 1000  269 Nov 30  2023 readme.txt
```

Now, keep in mind that I did **not** erase the persistent store. Also, the container was still running when I changed the service definition to deactivate the second volume-mapping. The `up` just recreated the container. In other words, the **effect** of the implied:

```
sudo mkdir ./volumes/domoticz/www/templates
```

from the second volume-mapping was still in force. I mention this because it is likely to be the situation faced by anyone who is upgrading to the `latest` image, save that they may still have the blocking second volume-mapping in place.

As soon as I removed the blocking second volume-mapping, self-repair automatically fixed the templates folder by copying the files from the **internal** path:

```
/opt/domoticz/www/templates
```

to the **internal** path:

```
/opt/domoticz/userdata/www/templates
```

which corresponds with the **external** path:

```
./volumes/domoticz/www/templates
```

<hr>

So, why does IOTstack not have that second volume-mapping? I have no idea. It seems to have been that way since the get-go. The initial log entry is:

```
commit ff523e0fbbb526f978a3f51433db0aa6fcef0640
Author: Ctrl-F4 <48384485+Ctrl-F4@users.noreply.github.com>
Date:   Thu Jan 16 15:24:52 2020 +0100

    Create service.yml
    
    added support for domoticz
```

I have no idea who "Ctrl-F4" is. Changes since have been mostly either cosmetic or to adapt to other things happening in IOTstack. Nobody using this service definition has ever popped up to say "hey - over at the Domoticz doco there's another volume mapping - how come we're not using it?" Had that happened, we would probably have had this discussion before.

Also, please don't mis-read this as me playing a kind of "gotcha" game because I'm not doing that. Elsewhere in the DockerHub doco you have:

```
docker run -d \
    -p 8080:8080 \
    -p 8443:443 \
    -v <path for config files>:/opt/domoticz/userdata \
    -e TZ=Europe/Amsterdam
    --device=<device_id> \
    --name=<container name> \ 
    domoticz/domoticz
```

That's a single volume mapping. And, then, when I look at the "blame" display for the main README it looks like this second volume mapping only just got added… 

… which means I'm now totally confused.

**Comment by Paraphraser** [comment]
I should also add that if you remove the second volume-mapping and you continue to have trouble then you're going to need to share your **entire** service definition so I can try to play along.

**Comment by gizmocuz** [comment]
Thanks for the very informative response! I have read it a few times and learned a lot again about docker, thanks!

Now all you said is correct, up till your last comment

> I should also add that if you remove the second volume-mapping and you continue to have trouble then you're going to need to share your entire service definition so I can try to play along.

😂🤣

I added the extra volume line on our docker hub as well as on our github. I just removed it.. but I need to add it back again.....

So, with your previous post and running the container, not having the second volume line, indeed the files are copied to my system. Great!
But.... Domoticz does not see the www/templates folder on my side, only it's own folder, and there where no custom templates enabled in that folder.

As soon as I add my second volume line, issues a docker down/stop and up, Domoticz sees my folder and custom page is working

**Comment by Paraphraser** [comment]
Well, that's a separate problem to the one I thought we were discussing.

It can be solved in one of two ways. The **preferred** way would be to pass the path to `domoticz` (the process) when it launches inside the container. Now it's:

```
/opt/domoticz/domoticz \
   -www 8080 -noupdates \
   -sslwww 443 \
   -userdata /opt/domoticz/userdata
```

and it would need to be augmented to:

```
/opt/domoticz/domoticz \
   -www 8080 -noupdates \
   -sslwww 443 \
   -userdata /opt/domoticz/userdata \
   -wwwroot /opt/domoticz/userdata/www
```

**BUT**, I interpret that (possibly wrongly) as `domoticz` (the process) expecting **ALL** of `/opt/domoticz/www` (which is the default if `--wwwroot` is omitted) needing to be copied into `userdata/www`. If you recall, that's what an earlier version of the pull request was doing but we walked it back to just the templates.

> I'm not saying I had a reason for doing it the other way in the first place - I just did what seemed logical at the time. No better than that.

The alternative is a trick I've used before when the process running inside the container didn't have a useful command-line option. It involves a double-copy.  First, `rclone` would do as now and perform a "no clobber" copy of the image templates to the persistent store (as in self-repair). Second, `rclone` would perform an overwrite copy back the other way. That would pick up any changes made in the persistent store, as well as new files added to the persistent store. The problem is that you'd need to restart the container before the copy would be triggered. You have to do that with some containers (eg Node-RED) but it's suboptimal.

Of the two, the command-line option is the better choice, but potentially at the price of needing to copy the entire www folder.

Thoughts?

<hr>

Whatever we do, that second volumes statement won't help anything.

**Comment by Paraphraser** [comment]
Hmmm. Well, I did a test setup adding the -wwwroot flag and setting up `rclone` to copy www but I'm getting

```
2024-06-08 18:33:22.846  Status: WebServer(HTTP) startup failed on address :: with port: 8080: resolve: Host not found (authoritative) [asio.netdb:1 at /usr/local/include/boost/asio/detail/resolver_service.hpp:84 in function 'resolve'], trying ::
2024-06-08 18:33:22.846  Status: WebServer(HTTP) startup failed on address :: with port: 8080: resolve: Host not found (authoritative) [asio.netdb:1 at /usr/local/include/boost/asio/detail/resolver_service.hpp:84 in function 'resolve'], trying 0.0.0.0
```

which doesn't make a whole lot of sense, in context. I'll do a bit more digging.

**Comment by Paraphraser** [comment]
Figured it out. `domoticz` (the command) has a bug in its usage:

```
$ docker exec domoticz /opt/domoticz/domoticz --help | grep "\-wwwroot"
	-wwwroot file_path (for example /opt/domoticz/www)
```

I read that as implying that the default is `/opt/domoticz/www` and that, by inference, if you copied that path to somewhere else, you'd pass `-wwwroot` pointing to the same relative position. So:

```
-wwwroot /opt/domoticz/userdata/www
```

But it turns out that there's another `www` folder one level down, so the argument needs to be:

```
-wwwroot /opt/domoticz/userdata/www/www
```

As soon as I do that I can connect to the Web UI with all the files at the external path (in my case, with IOTstack conventions):

```
./volumes/domoticz/www/www
```

Do you want me to prepare a new PR on that basis?

**Comment by Paraphraser** [comment]
I take back everything I said in the earlier post.

I have got it working but I was wrong about the bug in the usage.

**Pull request merged**
