### PR TITLE
Refactor builder

### PR DESCRIPTION
**Pull request by markruys**
Changes:

* Add EXTRA_PACKAGES environment variable for user to, well, add extra packages
* Add support to build on macOS
* Simplify Dockerfile
* Simplify build.sh and buildstable.sh
* Update documentation

### CODE REVIEW

**Comment by markruys** [comment]
Note that the original Domoticz Docker images have a flaw: the tags do not relate to the Domoticz version installed. This is because this image always installs the latest beta/stable tarball. This PR moves the tarball into the image, so that you install the correct version.

Furthermore, I think that the `build.sh` environment variable should not be hardcoded into the script. It should either be a parameter, or deferred from the `version.h` contents somehow.

**Comment by gizmocuz** [comment]
Thank you for this PR and the changes!!!

Will this not make the image larger because you are pulling the tarbal into the image ?

Could you leave the "Domoticz - http://www.domoticz.com/" in the readme at the top.
It is much easier for users to directly click on this.

Could you keep the buildstable script, sure you make call the original build script, but I want to use this to build the stable (when it's out)

**Comment by markruys** [comment]
I think it's a good thing to pull the Domoticz into the image, that's what you want to deploy after all. If you really want to download Domoticz during image install from an external source, you should version and keep all builds of the Domoticz tarball and not reuse the same generic tarball name for different builds. You don't to do that, do you? But really, I don't see any serious advantage not to pack it into the image. That's the whole point of container images, isn't it?

I'll add the notice, not problem.

I could add a symlink of `buildstable` to `build` (and let it set the RELEASE variable), would that work for you? I don't like code duplication even for small scripts as this build tool. An alternative would be to move the code to a shared lib to include.

**Comment by gizmocuz** [comment]
maybe call the build.sh script from buildstable with the RELEASE variable ?

**Comment by gizmocuz** [comment]
Thank you very much for this PR and time! Sorry about the delay!

**Comment by gizmocuz** [comment]
I updated the readme as python3-requests is now by default included by your PR

**Pull request merged**
