### PR TITLE
Adding multiple tags

### PR DESCRIPTION
**Pull request by RobbITbv**
* Add Beta version for tag purpose
* Add multiple tags to the docker build echo

Reference to https://github.com/domoticz/domoticz/issues/4810

This should give you an idea for multiple tags. I made some assumptions with the version.

I also created a stable folder which could be used in the stable build process. I did not get a chance to investigate the build process or do any other deep dives. So these changes should work in theory, but I did not get a chance to test it myself. I just added the tags. Please let me know how I can assist you for more docker related issues.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for the PR!!!

Do you think it is possible to use the same Dockerfile because the only difference is

curl -k -L https://releases.domoticz.com/releases/release/${archive_file} --output domoticz.tgz \
curl -k -L https://releases.domoticz.com/releases/beta/${archive_file} --output domoticz.tgz \

**release/beta**

Maybe you can supply it as argument like APP_VERSION/APP_HASH/BUILD_DATE and call it GIT_BRANCH (with the word beta or release) and then issue

curl -k -L https://releases.domoticz.com/releases/release/$GIT_BRANCH --output domoticz.tgz \

**Comment by RobbITbv** [comment]
Something like this? If STABLE is provided it should download release otherwise it should download the beta build. I did not have time to test this, my apologies. I moved the stable build script as well. Let me know if this helps you further!

**Comment by gizmocuz** [comment]
That looks perfect, hope it works ;)

I am doing some reading about tags: (specially latest)

https://vsupalov.com/docker-latest-tag/

Should we also tag the beta builds as **latest-beta** ?

In this case a user can always specify to go for the latest-stable or latest-beta ?

**Comment by gizmocuz** [comment]
Thank you for this PR and work!!

**Pull request merged**
